name: 🧊 GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: '0 18 * * *'   # chạy mỗi ngày 18:00 UTC
  workflow_dispatch:        # cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Contributions (Night Green)
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Profile 3D (Night Green)
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: khoalearningcode
        with:
          args: --theme "night-green"

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "🧊 Update 3D contributions (night-green)"
          git push
