name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake with calendar labels
        uses: Platane/snk@v3
        with:
          github_user_name: khoalearningcode
          outputs: |
            dist/snake.svg
            dist/snake.gif
          palette: "github-dark"
          # bật nhãn tháng/ngày
          enable_calendar: true

      - name: Verify build output
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
