name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Snake với màu giống GitHub chart
      - name: Generate Snake files
        uses: Platane/snk@v3
        with:
          github_user_name: khoalearningcode
          outputs: |
            dist/snake.svg
            dist/snake.gif
          palette: "github-dark"
          snake_color: "#239a3b"     # xanh lá đậm (giống ô contributions)
          snake_head: "#40c463"     # xanh lá sáng (làm nổi phần đầu)
          snake_tail: "#161b22"     # màu nền GitHub dark
          color_snake: "true"

      - name: Verify build output
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
