name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # chạy mỗi ngày lúc 0h UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake (xuất ra file snake.svg)
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: khoalearningcode
          outputs: |
            dist/snake.svg

      # Debug: in ra file vừa tạo
      - name: List build dir
        run: ls -R dist

      # Deploy ra branch `output`
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
