name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # chạy mỗi ngày lúc 0h UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake files
        uses: Platane/snk@v3
        with:
          github_user_name: khoalearningcode
          outputs: |
            dist/snake.svg
            dist/snake.gif
          palette: "github-dark"    # màu contribution giống GitHub dark
          enable_calendar: true     # hiện ngày & tháng trên chart
          snake_color: "#239a3b"    # xanh lá trầm (giống ô contributions)
          snake_head: "#40c463"     # đầu rắn sáng hơn để nổi bật
          snake_tail: "#161b22"     # đuôi rắn cùng màu nền dark

      - name: Verify build output
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
