name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # chạy mỗi ngày lúc 0h UTC
  workflow_dispatch:      # cho phép chạy thủ công
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: khoalearningcode
          outputs: dist/snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output   # branch chứa file snake.svg
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
